Repository amosproj/amos2024ws04-personalized-play, pull requests merged in 2024-11, with the labels that each got.

#32 FEAT: SignUp page
  app/assets/signup.png
  app/src/screens/SignUp.tsx
  app/src/types/index.d.ts
Labels: release: feature

#31 FEAT: Base App navigation and User Auth with custom Formik form component
  .gitignore
  app/App.tsx
  app/app.json
  app/assets/landing.png
  app/assets/signup.png
  app/babel.config.js
  app/biome.json
  app/components.json
  app/global.css
  app/package-lock.json
  app/package.json
  app/shadcn/components/index.ts
  app/shadcn/components/ui/button.tsx
  app/shadcn/components/ui/index.ts
  app/shadcn/components/ui/input.tsx
  app/shadcn/components/ui/label.tsx
  app/shadcn/components/ui/text.tsx
  app/shadcn/components/ui/typography.tsx
  app/shadcn/icons/Eye.tsx
  app/shadcn/icons/EyeClosed.tsx
  app/shadcn/icons/Fingerprint.tsx
  app/shadcn/icons/Mail.tsx
  app/shadcn/icons/RotateCw.tsx
  app/shadcn/icons/iconWithClassName.ts
  app/shadcn/icons/index.ts
  app/shadcn/lib/constants.ts
  app/shadcn/lib/index.ts
  app/shadcn/lib/useColorScheme.tsx
  app/shadcn/lib/utils.ts
  app/src/App.tsx
  app/src/components/Drawer.tsx
  app/src/components/FormikSubmitButton.tsx
  app/src/components/FormikTextInput.tsx
  app/src/components/GoogleSignInButton.tsx
  app/src/components/Header.tsx
  app/src/components/IconGoogle.tsx
  app/src/components/ThemeProvider.tsx
  app/src/components/index.ts
  app/src/constants/firebase.ts
  app/src/constants/index.ts
  app/src/constants/screens.ts
  app/src/hooks/index.ts
  app/src/index.ts
  app/src/routes/AppRoutes.tsx
  app/src/routes/AuthRoutes.tsx
  app/src/routes/UnAuthRoutes.tsx
  app/src/routes/index.ts
  app/src/screens/ForgotPassword.tsx
  app/src/screens/Home.tsx
  app/src/screens/Landing.tsx
  app/src/screens/Loading.tsx
  app/src/screens/Profile.tsx
  app/src/screens/ResetPassword.tsx
  app/src/screens/SignIn.tsx
  app/src/screens/SignUp.tsx
  app/src/screens/index.ts
  app/src/types/index.d.ts
  app/tailwind.config.js
  app/tsconfig.json
Labels: release: feature

#48 FEAT: Add playtime onboarding question
  app/src/components/ContextualQuestionPlayTime.tsx
  app/src/components/Slider.tsx
  app/src/screens/Onboarding.tsx
  app/src/types/OnboardingType.ts
Labels: release: feature

#49 Feat/app auth flow user age
  app/assets/onboarding.jpg
  app/src/components/ContextualQuestionAgeKids.tsx
  app/src/screens/Onboarding.tsx
  app/src/types/OnboardingType.ts
Labels: release: feature

#50 FIX: Add missing dependency for slider
  app/package-lock.json
  app/package.json
Labels: release: bug-fix

#51 FIX: The next button in the onboarding screen is now disabled if the current question is not answered
  app/package-lock.json
  app/src/components/ContextualQuestionNumberKids.tsx
  app/src/components/ContextualQuestionPlayTime.tsx
  app/src/components/index.ts
  app/src/screens/Onboarding.tsx
  app/src/screens/index.ts
  app/tsconfig.json
Labels: release: bug-fix

#71 FIX(energylevel): Adjust image container && Question font && margin
  app/src/components/ContextualQuestionEnergyLevel.tsx
Labels: release: bug-fix

#73 FEAT: Loading screen
  app/assets/fonts/Inter-Bold.ttf
  app/assets/fonts/Inter-Regular.ttf
  app/assets/mumbilogo-grey-animated.gif
  app/assets/mumbilogo-grey.png
  app/package-lock.json
  app/package.json
  app/src/constants/screens.ts
  app/src/routes/UnAuthRoutes.tsx
  app/src/screens/Loading.tsx
  install.sh
Labels: release: feature

#72 CHORE: update expo and related dependencies to latest versions
  app/package-lock.json
  app/package.json
Labels: release: chore

#75 CI: Add Google services config and firebase config to EAS workflow
  .easignore
  .github/workflows/eas-pr-preview.yml
  app/src/App.tsx
Labels: release: ci-cd

#76 Feat: Implement custom font loading and enhance loading screen
  app/assets/fonts/Inter-Bold.ttf
  app/assets/fonts/Inter-Light.ttf
  app/assets/fonts/Inter-SemiBold.ttf
  app/assets/mumbilogo-grey-animated.gif
  app/src/App.tsx
  app/src/constants/fonts.ts
  app/src/constants/index.ts
  app/src/screens/Loading.tsx
Labels: release: feature

#83 FEAT: Re-design Activity Choice screen
  app/assets/activity.json
  app/src/components/ContextualQuestionActivityChoice.tsx
  app/src/screens/Onboarding.tsx
Labels: release: feature

#84 FEAT: Re-design energy level input screen
  app/src/components/ContextualQuestionEnergyLevel.tsx
  app/src/screens/Onboarding.tsx
Labels: release: feature

#86 FEAT: Playtime Question Redesign and logic improve using Formik
  app/src/components/ContextualQuestionPlayTime.tsx
  app/src/screens/Onboarding.tsx
Labels: release: feature

#87 FEAT: Re-design kids details input screen
  app/package-lock.json
  app/package.json
  app/shadcn/components/ui/avatar.tsx
  app/src/components/ContextualQuestionAgeKids.tsx
  app/src/components/ContextualQuestionNumberKids.tsx
  app/src/components/FormikTextInput.tsx
  app/src/screens/Onboarding.tsx
  app/src/types/index.d.ts
Labels: release: feature
