Repository amosproj/amos2024ws04-personalized-play, pull requests merged in 2024-12, with the labels that each got.

#102 feat: Added skill question screen
  app/assets/skill.json
  app/package-lock.json
  app/package.json
  app/shadcn/components/ui/checkbox.tsx
  app/shadcn/lib/icons/Check.tsx
  app/shadcn/lib/icons/iconWithClassName.ts
  app/src/components/ContextualQuestionSkill.tsx
  app/src/components/index.ts
  app/src/screens/Onboarding.tsx
Labels: release: feature

#103 DOC(readme): update readme
  README.md
Labels: release: documentation

#113 CI: Version bump of `biome.js` from `^1.9.4` to `1.9.4`
  app/package-lock.json
  app/package.json
  backend/package-lock.json
  backend/package.json
Labels: release: ci-cd

#88 feat(InfoAlert): Info Alert Comp
  app/package-lock.json
  app/package.json
  app/shadcn/components/ui/alert-dialog.tsx
  app/src/App.tsx
  app/src/components/ContextualQuestionActivityChoice.tsx
  app/src/components/InfoAlert.tsx
Labels: release: feature

#101 FEAT: Add Question To Take a Picture (Items In Hand)
  app/package-lock.json
  app/package.json
  app/shadcn/icons/Camera.tsx
  app/shadcn/icons/index.ts
  app/src/components/ContextualQuestionCamera.tsx
  app/src/components/ContextualQuestionDetectedItems.tsx
  app/src/components/index.ts
  app/src/screens/Onboarding.tsx
Labels: release: feature

#100 FEAT: Save user onboarding data to firestore
  app/src/constants/firebase.ts
  app/src/screens/Onboarding.tsx
Labels: release: feature

#115 Feat/display items identified
  app/package-lock.json
  app/package.json
  app/src/components/ContextualQuestionDetectedItems.tsx
  app/src/components/ContextualQuestionDisplayItemsIdentified.tsx
  app/src/components/index.ts
  app/src/screens/Onboarding.tsx
  app/src/types/index.d.ts
  backend/package-lock.json
Labels: release: feature

#117 FEAT: Genkit Chors flow
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/ai/flows/chors/agent.ts
  backend/src/ai/flows/chors/flow.ts
  backend/src/ai/flows/chors/helpers.ts
  backend/src/ai/flows/chors/index.ts
  backend/src/ai/flows/chors/schema.ts
  backend/src/ai/flows/index.ts
  backend/src/constants/index.ts
  backend/src/firebase/services.ts
  backend/src/types/index.d.ts
Labels: release: feature

#114 FEAT: Add health considerations field on the kid input page
  app/package-lock.json
  app/package.json
  app/shadcn/components/ui/radio-group.tsx
  app/shadcn/components/ui/switch.tsx
  app/src/components/ContextualQuestionAgeKids.tsx
  app/src/types/index.d.ts
Labels: release: feature

#122 FEAT: Add Feedback Screen
  app/shadcn/icons/Brain.tsx
  app/shadcn/icons/Heart.tsx
  app/shadcn/icons/Home.tsx
  app/shadcn/icons/ThumbsDown.tsx
  app/shadcn/icons/ThumbsUp.tsx
  app/shadcn/icons/index.ts
  app/src/components/FavouriteButton.tsx
  app/src/screens/Feedback.tsx
  app/src/screens/Onboarding.tsx
  app/src/screens/index.ts
Labels: release: feature
