Repository amosproj/amos2024ws04-personalized-play, pull requests merged in 2025-01, with the labels that each got.

#136 feat(selectKids): handle Formik
  app/src/components/ContextualQuestionSelectKids.tsx
  app/src/screens/NewPlay.tsx
Labels: release: feature

#135 feat: updated build script to build both dev build with single command
  app/package-lock.json
Labels: release: feature

#131 FEAT: start new play
  app/shadcn/components/ui/card.tsx
  app/src/components/ContextualQuestionSelectKids.tsx
  app/src/components/index.ts
  app/src/constants/screens.ts
  app/src/routes/AuthRoutes.tsx
  app/src/screens/Home.tsx
  app/src/screens/NewPlay.tsx
  app/src/screens/index.ts
  app/src/types/index.d.ts
Labels: release: feature

#137 FEAT: Add chore type selection inside a modal
  app/package-lock.json
  app/package.json
  app/src/components/ChoreTypeSelector.tsx
  app/src/components/ChoresButtonModal.tsx
  app/src/components/ContextualQuestionActivityChoice.tsx
  app/src/components/index.ts
  app/src/screens/Onboarding.tsx
  app/src/types/index.d.ts
Labels: release: feature

#128 FEAT: Add Favorite Activities Screen
  app/src/components/EditActivityButton.tsx
  app/src/components/index.ts
  app/src/constants/screens.ts
  app/src/routes/AuthRoutes.tsx
  app/src/screens/Favorite.tsx
  app/src/screens/Onboarding.tsx
  app/src/screens/index.ts
  app/src/types/index.d.ts
Labels: release: feature

#163 Feat/slider info popup
  app/src/components/ContextualQuestionPlayTime.tsx
  app/src/routes/AuthRoutes.tsx
Labels: release: feature

#164 FEAT: Add Chat UI, Code Refactoring and Bug Fixes
  app/app.json
  app/package-lock.json
  app/package.json
  app/src/components/ContextualQuestionActivityChoice.tsx
  app/src/components/ContextualQuestionAgeKids.tsx
  app/src/components/ContextualQuestionCamera.tsx
  app/src/components/ContextualQuestionDisplayItemsIdentified.tsx
  app/src/components/ContextualQuestionEnergyLevel.tsx
  app/src/components/ContextualQuestionSkill.tsx
  app/src/components/ContextualQuestionUserName.tsx
  app/src/components/FormikSubmitButton.tsx
  app/src/components/FormikTextInput.tsx
  app/src/components/GoogleSignInButton.tsx
  app/src/components/Loading.tsx
  app/src/components/index.ts
  app/src/constants/index.ts
  app/src/constants/screens.ts
  app/src/constants/skills.ts
  app/src/hooks/index.ts
  app/src/hooks/useGetActivity.ts
  app/src/routes/AppRoutes.tsx
  app/src/routes/AuthRoutes.tsx
  app/src/routes/UnAuthRoutes.tsx
  app/src/screens/ActivityPlayer.tsx
  app/src/screens/Onboarding.tsx
  app/src/screens/SignIn.tsx
  app/src/screens/SignUp.tsx
  app/src/screens/index.ts
  app/src/types/OnboardingType.ts
  app/src/types/index.d.ts
  backend/package-lock.json
  backend/package.json
  backend/src/ai/flows/chors/flow.ts
  backend/src/firebase/services.ts
  backend/src/functions/index.ts
Labels: release: feature

#168 Feat/reload activity
  app/package.json
  app/src/hooks/useGetActivity.ts
  app/src/screens/ActivityPlayer.tsx
  app/src/screens/Favorite.tsx
Labels: release: feature

#175 FEAT: add robot.txt
  Robot.txt
Labels: release: feature, release: documentation

#167 FEAT: NewKidForm
  app/src/components/ContextualQuestionNumberNewKids.tsx
  app/src/components/HealthConsiderationsDialog.tsx
  app/src/components/index.ts
  app/src/constants/screens.ts
  app/src/routes/AuthRoutes.tsx
  app/src/screens/Home.tsx
  app/src/screens/NewKid.tsx
  app/src/screens/Profile.tsx
  app/src/screens/index.ts
  app/src/types/index.d.ts
Labels: release: feature

#169 Refactor: onboarding and fix new play onboarding
  app/src/components/ContextualQuestionActivityChoice.tsx
  app/src/components/ContextualQuestionAgeKids.tsx
  app/src/components/ContextualQuestionCamera.tsx
  app/src/components/ContextualQuestionSelectKids.tsx
  app/src/screens/Favorite.tsx
  app/src/screens/Home.tsx
  app/src/screens/NewPlay.tsx
  app/src/screens/Onboarding.tsx
  app/src/types/index.d.ts
Labels: release: refactor

#180 FEAT: Add finish button and integrate with feedback screen
  app/src/constants/screens.ts
  app/src/routes/AuthRoutes.tsx
  app/src/screens/ActivityPlayer.tsx
  app/src/screens/Feedback.tsx
  app/src/screens/NewKid.tsx
Labels: release: feature

#181 Refactor/homescreen
  app/src/screens/Home.tsx
Labels: release: refactor

#173 Refactor:profile page and add add new kid button
  app/src/components/DeleteAlert.tsx
  app/src/components/HealthConsiderationsDialog.tsx
  app/src/screens/Profile.tsx
Labels: release: refactor
